version: '3.8'

services:
  app:
    image: node:18-alpine
    command: yarn dev
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      PORT: 4000
      APP_HASH: guilherme
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 102030
      MYSQL_DATABASE: website_admin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

networks:
  default:
    name: app-network
    driver: bridge